language: python
python:
  - "3.9"

addons:
  chrome: stable

install:
  - pip install -r requirements.txt

before_script:
  - python app/app.py & # run the server in a background process in the Travis CI environment

script:
  - python -m pytest tests/