language: python
python:
  - "3.9"

addons:
  chrome: stable

before_install:
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

install:
  - pip install -r requirements.txt

before_script:
  - python app/app.py & # run the server in a background process in the Travis CI environment

script:
  - python -m pytest tests/

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: bmi-calculator-heston
  on:
    branch: main
  skip_cleanup: true
