language: python
python:
  - "3.9"

env:
global:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN

addons:
  chrome: stable

before_install:
  - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku https://git.heroku.com/bmi-calculator-heston.git
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install -r requirements.txt

before_script:
  - python app/app.py & # run the server in a background process in the Travis CI environment

script:
  - coverage run --source=. -m pytest tests/
  - coverage report
  - ./format.sh

after_success:
  - coveralls

deploy:
  provider: script
  script: bash deploy_heroku.sh
  cleanup: false
  on:
    branch: main