language: python
python:
  - "3.9"

addons:
  chrome: stable

install:
  - pip install -r requirements.txt

before_script:
  - CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$(google-chrome --version | awk '{ print $3 }' | cut -d '.' -f 1-3))
  - wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/

script:
  - python -m pytest tests/